#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JoyReactor.AndroidTv.Resource", IsApplication=true)]

namespace JoyReactor.AndroidTv
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::JoyReactor.AndroidTv.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::JoyReactor.AndroidTv.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::JoyReactor.AndroidTv.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::JoyReactor.AndroidTv.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::JoyReactor.AndroidTv.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::JoyReactor.AndroidTv.Resource.String.Hello;
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int lb_playback_bg_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int lb_playback_bg_fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int lb_playback_controls_fade_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int lb_playback_controls_fade_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int lb_playback_description_fade_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int lb_playback_description_fade_out = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int lb_playback_rows_fade_in = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int lb_playback_rows_fade_out = 2130968583;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01002b
			public const int activatedAnimationDuration = 2130772011;
			
			// aapt resource value: 0x7f010011
			public const int baseCardViewStyle = 2130771985;
			
			// aapt resource value: 0x7f010003
			public const int browsePaddingBottom = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int browsePaddingLeft = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int browsePaddingRight = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int browsePaddingTop = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int browseRowsFadingEdgeLength = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int browseRowsMarginStart = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int browseRowsMarginTop = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int browseTitleIconStyle = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int browseTitleTextStyle = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int browseTitleViewStyle = 2130771977;
			
			// aapt resource value: 0x7f010026
			public const int cardType = 2130772006;
			
			// aapt resource value: 0x7f010042
			public const int closed_captioning = 2130772034;
			
			// aapt resource value: 0x7f010047
			public const int columnWidth = 2130772039;
			
			// aapt resource value: 0x7f01001b
			public const int defaultBrandColor = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int defaultSearchBrightColor = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int defaultSearchColor = 2130771996;
			
			// aapt resource value: 0x7f01001f
			public const int defaultSearchIcon = 2130771999;
			
			// aapt resource value: 0x7f010016
			public const int detailsActionButtonStyle = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int detailsDescriptionBodyStyle = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int detailsDescriptionSubtitleStyle = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int detailsDescriptionTitleStyle = 2130771987;
			
			// aapt resource value: 0x7f01001a
			public const int errorMessageStyle = 2130771994;
			
			// aapt resource value: 0x7f010028
			public const int extraVisibility = 2130772008;
			
			// aapt resource value: 0x7f010036
			public const int fast_forward = 2130772022;
			
			// aapt resource value: 0x7f01002e
			public const int focusOutEnd = 2130772014;
			
			// aapt resource value: 0x7f01002d
			public const int focusOutFront = 2130772013;
			
			// aapt resource value: 0x7f01000b
			public const int headerStyle = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int headersVerticalGridStyle = 2130771978;
			
			// aapt resource value: 0x7f010041
			public const int high_quality = 2130772033;
			
			// aapt resource value: 0x7f01002f
			public const int horizontalMargin = 2130772015;
			
			// aapt resource value: 0x7f010012
			public const int imageCardViewStyle = 2130771986;
			
			// aapt resource value: 0x7f010033
			public const int infoAreaBackground = 2130772019;
			
			// aapt resource value: 0x7f010027
			public const int infoVisibility = 2130772007;
			
			// aapt resource value: 0x7f010019
			public const int itemsVerticalGridStyle = 2130771993;
			
			// aapt resource value: 0x7f01002c
			public const int layout_viewType = 2130772012;
			
			// aapt resource value: 0x7f010048
			public const int numberOfColumns = 2130772040;
			
			// aapt resource value: 0x7f010032
			public const int numberOfRows = 2130772018;
			
			// aapt resource value: 0x7f010024
			public const int overlayDimActiveLevel = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int overlayDimDimmedLevel = 2130772005;
			
			// aapt resource value: 0x7f010023
			public const int overlayDimMaskColor = 2130772003;
			
			// aapt resource value: 0x7f010035
			public const int pause = 2130772021;
			
			// aapt resource value: 0x7f010034
			public const int play = 2130772020;
			
			// aapt resource value: 0x7f010022
			public const int playbackControlsActionIcons = 2130772002;
			
			// aapt resource value: 0x7f010017
			public const int playbackControlsButtonStyle = 2130771991;
			
			// aapt resource value: 0x7f010021
			public const int playbackControlsIconHighlightColor = 2130772001;
			
			// aapt resource value: 0x7f010018
			public const int playbackControlsTimeStyle = 2130771992;
			
			// aapt resource value: 0x7f010020
			public const int playbackProgressPrimaryColor = 2130772000;
			
			// aapt resource value: 0x7f01003e
			public const int repeat = 2130772030;
			
			// aapt resource value: 0x7f01003f
			public const int repeat_one = 2130772031;
			
			// aapt resource value: 0x7f010037
			public const int rewind = 2130772023;
			
			// aapt resource value: 0x7f01000e
			public const int rowHeaderStyle = 2130771982;
			
			// aapt resource value: 0x7f010031
			public const int rowHeight = 2130772017;
			
			// aapt resource value: 0x7f01000d
			public const int rowHorizontalGridStyle = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int rowHoverCardDescriptionStyle = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int rowHoverCardTitleStyle = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int rowsVerticalGridStyle = 2130771980;
			
			// aapt resource value: 0x7f010046
			public const int searchOrbBrightColor = 2130772038;
			
			// aapt resource value: 0x7f010045
			public const int searchOrbColor = 2130772037;
			
			// aapt resource value: 0x7f010043
			public const int searchOrbIcon = 2130772035;
			
			// aapt resource value: 0x7f010044
			public const int searchOrbIconColor = 2130772036;
			
			// aapt resource value: 0x7f01001e
			public const int searchOrbViewStyle = 2130771998;
			
			// aapt resource value: 0x7f010029
			public const int selectedAnimationDelay = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int selectedAnimationDuration = 2130772010;
			
			// aapt resource value: 0x7f010040
			public const int shuffle = 2130772032;
			
			// aapt resource value: 0x7f010038
			public const int skip_next = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int skip_previous = 2130772025;
			
			// aapt resource value: 0x7f01003d
			public const int thumb_down = 2130772029;
			
			// aapt resource value: 0x7f01003c
			public const int thumb_down_outline = 2130772028;
			
			// aapt resource value: 0x7f01003b
			public const int thumb_up = 2130772027;
			
			// aapt resource value: 0x7f01003a
			public const int thumb_up_outline = 2130772026;
			
			// aapt resource value: 0x7f010030
			public const int verticalMargin = 2130772016;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int lb_action_text_color = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int lb_background_protection = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int lb_basic_card_bg_color = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int lb_basic_card_content_text_color = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int lb_basic_card_info_bg_color = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int lb_basic_card_title_text_color = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int lb_browse_header_color = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int lb_browse_title_color = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int lb_control_button_color = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int lb_default_brand_color = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int lb_default_search_color = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int lb_details_description_body_color = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int lb_details_description_color = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int lb_details_overview_bg_color = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int lb_error_background_color_opaque = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int lb_error_background_color_translucent = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int lb_error_message_color_on_opaque = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int lb_error_message_color_on_translucent = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int lb_grey = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int lb_list_item_unselected_text_color = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int lb_playback_background_progress_color = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int lb_playback_controls_background_dark = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int lb_playback_controls_background_light = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int lb_playback_controls_time_text_color = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int lb_playback_icon_highlight_no_theme = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int lb_playback_progress_color_no_theme = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int lb_playback_secondary_progress_color = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int lb_search_bar_hint = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int lb_search_bar_hint_speech_mode = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int lb_search_bar_text = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int lb_search_bar_text_speech_mode = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int lb_search_plate_hint_text_color = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int lb_speech_orb_not_recording = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int lb_speech_orb_not_recording_icon = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int lb_speech_orb_not_recording_pulsed = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int lb_speech_orb_recording = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int lb_view_dim_mask_color = 2131296292;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0000
			public const int lb_action_1_line_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int lb_action_2_lines_height = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int lb_action_button_corner_radius = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int lb_action_icon_margin = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int lb_action_padding_horizontal = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int lb_action_text_size = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int lb_action_with_icon_padding_left = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int lb_action_with_icon_padding_right = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int lb_basic_card_content_text_size = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int lb_basic_card_info_badge_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int lb_basic_card_info_height = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int lb_basic_card_info_padding = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int lb_basic_card_info_text_margin = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int lb_basic_card_main_height = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int lb_basic_card_main_width = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int lb_basic_card_title_text_size = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int lb_browse_expanded_row_no_hovercard_bottom_padding = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int lb_browse_expanded_selected_row_top_padding = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int lb_browse_header_fading_length = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int lb_browse_header_height = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int lb_browse_header_padding_right = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int lb_browse_header_select_duration = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int lb_browse_header_select_scale = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int lb_browse_header_text_size = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int lb_browse_headers_vertical_margin = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int lb_browse_headers_width = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int lb_browse_headers_z = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int lb_browse_item_horizontal_margin = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int lb_browse_item_vertical_margin = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int lb_browse_padding_bottom = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int lb_browse_padding_left = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int lb_browse_padding_right = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int lb_browse_padding_top = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int lb_browse_row_hovercard_description_font_size = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int lb_browse_row_hovercard_max_width = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int lb_browse_row_hovercard_title_font_size = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int lb_browse_rows_fading_edge = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int lb_browse_rows_margin_start = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int lb_browse_rows_margin_top = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int lb_browse_selected_row_top_padding = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int lb_browse_title_height = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int lb_browse_title_icon_height = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int lb_browse_title_icon_margin_right = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int lb_browse_title_icon_width = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int lb_browse_title_text_size = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int lb_browse_title_text_width = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int lb_control_button_diameter = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int lb_control_button_height = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int lb_control_button_secondary_diameter = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int lb_control_button_secondary_height = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public const int lb_control_icon_height = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int lb_control_icon_width = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int lb_details_description_body_line_spacing = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int lb_details_description_body_text_size = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int lb_details_description_subtitle_text_size = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int lb_details_description_title_baseline = 2131361847;
			
			// aapt resource value: 0x7f0a0038
			public const int lb_details_description_title_line_spacing = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int lb_details_description_title_text_size = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int lb_details_description_under_subtitle_baseline_margin = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int lb_details_description_under_title_baseline_margin = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int lb_details_overview_action_items_margin = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int lb_details_overview_action_select_duration = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int lb_details_overview_actions_fade_size = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int lb_details_overview_actions_height = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int lb_details_overview_actions_padding_left = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int lb_details_overview_actions_padding_right = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int lb_details_overview_description_margin_bottom = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int lb_details_overview_description_margin_left = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int lb_details_overview_description_margin_right = 2131361860;
			
			// aapt resource value: 0x7f0a0045
			public const int lb_details_overview_description_margin_top = 2131361861;
			
			// aapt resource value: 0x7f0a0046
			public const int lb_details_overview_height_large = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public const int lb_details_overview_height_small = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int lb_details_overview_image_margin_horizontal = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int lb_details_overview_image_margin_vertical = 2131361865;
			
			// aapt resource value: 0x7f0a004a
			public const int lb_details_overview_margin_bottom = 2131361866;
			
			// aapt resource value: 0x7f0a004b
			public const int lb_details_overview_margin_left = 2131361867;
			
			// aapt resource value: 0x7f0a004c
			public const int lb_details_overview_margin_right = 2131361868;
			
			// aapt resource value: 0x7f0a004d
			public const int lb_details_overview_z = 2131361869;
			
			// aapt resource value: 0x7f0a004e
			public const int lb_details_rows_align_top = 2131361870;
			
			// aapt resource value: 0x7f0a004f
			public const int lb_error_image_max_height = 2131361871;
			
			// aapt resource value: 0x7f0a0050
			public const int lb_error_message_max_width = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int lb_error_message_text_size = 2131361873;
			
			// aapt resource value: 0x7f0a0052
			public const int lb_error_under_image_baseline_margin = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int lb_error_under_message_baseline_margin = 2131361875;
			
			// aapt resource value: 0x7f0a0054
			public const int lb_list_row_height = 2131361876;
			
			// aapt resource value: 0x7f0a0055
			public const int lb_material_shadow_details_z = 2131361877;
			
			// aapt resource value: 0x7f0a0056
			public const int lb_material_shadow_focused_z = 2131361878;
			
			// aapt resource value: 0x7f0a0057
			public const int lb_material_shadow_normal_z = 2131361879;
			
			// aapt resource value: 0x7f0a0058
			public const int lb_playback_controls_align_bottom = 2131361880;
			
			// aapt resource value: 0x7f0a0059
			public const int lb_playback_controls_card_height = 2131361881;
			
			// aapt resource value: 0x7f0a005a
			public const int lb_playback_controls_child_margin_bigger = 2131361882;
			
			// aapt resource value: 0x7f0a005b
			public const int lb_playback_controls_child_margin_biggest = 2131361883;
			
			// aapt resource value: 0x7f0a005c
			public const int lb_playback_controls_child_margin_default = 2131361884;
			
			// aapt resource value: 0x7f0a005d
			public const int lb_playback_controls_margin_bottom = 2131361885;
			
			// aapt resource value: 0x7f0a005e
			public const int lb_playback_controls_margin_left = 2131361886;
			
			// aapt resource value: 0x7f0a005f
			public const int lb_playback_controls_margin_right = 2131361887;
			
			// aapt resource value: 0x7f0a0060
			public const int lb_playback_controls_padding_bottom = 2131361888;
			
			// aapt resource value: 0x7f0a0061
			public const int lb_playback_controls_time_text_size = 2131361889;
			
			// aapt resource value: 0x7f0a0062
			public const int lb_playback_controls_z = 2131361890;
			
			// aapt resource value: 0x7f0a0063
			public const int lb_playback_current_time_margin_start = 2131361891;
			
			// aapt resource value: 0x7f0a0064
			public const int lb_playback_description_margin_end = 2131361892;
			
			// aapt resource value: 0x7f0a0065
			public const int lb_playback_description_margin_start = 2131361893;
			
			// aapt resource value: 0x7f0a0066
			public const int lb_playback_description_margin_top = 2131361894;
			
			// aapt resource value: 0x7f0a0067
			public const int lb_playback_major_fade_translate_y = 2131361895;
			
			// aapt resource value: 0x7f0a0068
			public const int lb_playback_minor_fade_translate_y = 2131361896;
			
			// aapt resource value: 0x7f0a0069
			public const int lb_playback_time_padding_top = 2131361897;
			
			// aapt resource value: 0x7f0a006a
			public const int lb_playback_total_time_margin_end = 2131361898;
			
			// aapt resource value: 0x7f0a006b
			public const int lb_rounded_rect_corner_radius = 2131361899;
			
			// aapt resource value: 0x7f0a006c
			public const int lb_search_bar_edit_text_margin_left = 2131361900;
			
			// aapt resource value: 0x7f0a006d
			public const int lb_search_bar_height = 2131361901;
			
			// aapt resource value: 0x7f0a006e
			public const int lb_search_bar_hint_margin_left = 2131361902;
			
			// aapt resource value: 0x7f0a006f
			public const int lb_search_bar_icon_height = 2131361903;
			
			// aapt resource value: 0x7f0a0070
			public const int lb_search_bar_icon_margin_left = 2131361904;
			
			// aapt resource value: 0x7f0a0071
			public const int lb_search_bar_icon_width = 2131361905;
			
			// aapt resource value: 0x7f0a0072
			public const int lb_search_bar_inner_margin_bottom = 2131361906;
			
			// aapt resource value: 0x7f0a0073
			public const int lb_search_bar_inner_margin_top = 2131361907;
			
			// aapt resource value: 0x7f0a0074
			public const int lb_search_bar_items_height = 2131361908;
			
			// aapt resource value: 0x7f0a0075
			public const int lb_search_bar_items_layout_margin_top = 2131361909;
			
			// aapt resource value: 0x7f0a0076
			public const int lb_search_bar_items_margin_left = 2131361910;
			
			// aapt resource value: 0x7f0a0077
			public const int lb_search_bar_items_width = 2131361911;
			
			// aapt resource value: 0x7f0a0078
			public const int lb_search_bar_padding_left = 2131361912;
			
			// aapt resource value: 0x7f0a0079
			public const int lb_search_bar_padding_top = 2131361913;
			
			// aapt resource value: 0x7f0a007a
			public const int lb_search_bar_speech_orb_margin_left = 2131361914;
			
			// aapt resource value: 0x7f0a007b
			public const int lb_search_bar_speech_orb_size = 2131361915;
			
			// aapt resource value: 0x7f0a007c
			public const int lb_search_bar_text_size = 2131361916;
			
			// aapt resource value: 0x7f0a007d
			public const int lb_search_bar_unfocused_text_size = 2131361917;
			
			// aapt resource value: 0x7f0a007e
			public const int lb_search_browse_row_padding_left = 2131361918;
			
			// aapt resource value: 0x7f0a007f
			public const int lb_search_browse_rows_align_top = 2131361919;
			
			// aapt resource value: 0x7f0a0080
			public const int lb_search_orb_focused_z = 2131361920;
			
			// aapt resource value: 0x7f0a0081
			public const int lb_search_orb_margin_bottom = 2131361921;
			
			// aapt resource value: 0x7f0a0082
			public const int lb_search_orb_margin_left = 2131361922;
			
			// aapt resource value: 0x7f0a0083
			public const int lb_search_orb_margin_right = 2131361923;
			
			// aapt resource value: 0x7f0a0084
			public const int lb_search_orb_margin_top = 2131361924;
			
			// aapt resource value: 0x7f0a0085
			public const int lb_search_orb_size = 2131361925;
			
			// aapt resource value: 0x7f0a0086
			public const int lb_search_orb_unfocused_z = 2131361926;
			
			// aapt resource value: 0x7f0a0087
			public const int lb_vertical_grid_padding_bottom = 2131361927;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int lb_action_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int lb_action_bg_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int lb_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int lb_card_foreground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int lb_card_shadow_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int lb_card_shadow_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int lb_control_button_primary = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int lb_control_button_secondary = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int lb_headers_right_fading = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int lb_ic_actions_right_arrow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int lb_ic_card_info_text_fade = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int lb_ic_cc = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int lb_ic_fast_forward = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int lb_ic_fast_rewind = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int lb_ic_hq = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int lb_ic_in_app_search = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int lb_ic_loop = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int lb_ic_loop_one = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int lb_ic_more = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int lb_ic_pause = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int lb_ic_play = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int lb_ic_playback_loop = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int lb_ic_replay = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int lb_ic_sad_cloud = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int lb_ic_search_mic = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int lb_ic_search_mic_out = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int lb_ic_shuffle = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int lb_ic_skip_next = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int lb_ic_skip_previous = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int lb_ic_stop = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int lb_ic_thumb_down = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int lb_ic_thumb_down_outline = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int lb_ic_thumb_up = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int lb_ic_thumb_up_outline = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int lb_in_app_search_bg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int lb_in_app_search_shadow_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int lb_in_app_search_shadow_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int lb_playback_progress_bar = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int lb_rounded_rect_bg = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int lb_search_orb = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int lb_speech_orb = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int lb_text_dot_one = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int lb_text_dot_one_small = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int lb_text_dot_two = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int lb_text_dot_two_small = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int monoandroidsplash = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Fraction
		{
			
			// aapt resource value: 0x7f0b0000
			public const int lb_browse_header_unselect_alpha = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int lb_browse_rows_scale = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int lb_focus_zoom_factor_large = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int lb_focus_zoom_factor_medium = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int lb_focus_zoom_factor_small = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int lb_search_bar_speech_orb_max_level_zoom = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int lb_search_orb_focused_zoom = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int lb_view_active_level = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int lb_view_dimmed_level = 2131427336;
			
			static Fraction()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Fraction()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0012
			public const int activated = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int always = 2131492883;
			
			// aapt resource value: 0x7f0c005c
			public const int background_color = 2131492956;
			
			// aapt resource value: 0x7f0c005f
			public const int background_dim = 2131492959;
			
			// aapt resource value: 0x7f0c005e
			public const int background_imagein = 2131492958;
			
			// aapt resource value: 0x7f0c005d
			public const int background_imageout = 2131492957;
			
			// aapt resource value: 0x7f0c005b
			public const int background_theme = 2131492955;
			
			// aapt resource value: 0x7f0c0047
			public const int bottom_spacer = 2131492935;
			
			// aapt resource value: 0x7f0c0055
			public const int browse_badge = 2131492949;
			
			// aapt resource value: 0x7f0c001c
			public const int browse_container_dock = 2131492892;
			
			// aapt resource value: 0x7f0c001a
			public const int browse_dummy = 2131492890;
			
			// aapt resource value: 0x7f0c001b
			public const int browse_frame = 2131492891;
			
			// aapt resource value: 0x7f0c0058
			public const int browse_grid = 2131492952;
			
			// aapt resource value: 0x7f0c0059
			public const int browse_grid_dock = 2131492953;
			
			// aapt resource value: 0x7f0c0031
			public const int browse_headers = 2131492913;
			
			// aapt resource value: 0x7f0c001d
			public const int browse_headers_dock = 2131492893;
			
			// aapt resource value: 0x7f0c0057
			public const int browse_orb = 2131492951;
			
			// aapt resource value: 0x7f0c0056
			public const int browse_title = 2131492950;
			
			// aapt resource value: 0x7f0c001e
			public const int browse_title_group = 2131492894;
			
			// aapt resource value: 0x7f0c0020
			public const int button = 2131492896;
			
			// aapt resource value: 0x7f0c005a
			public const int container = 2131492954;
			
			// aapt resource value: 0x7f0c004a
			public const int container_list = 2131492938;
			
			// aapt resource value: 0x7f0c0036
			public const int content_text = 2131492918;
			
			// aapt resource value: 0x7f0c001f
			public const int control_bar = 2131492895;
			
			// aapt resource value: 0x7f0c0042
			public const int controls_card = 2131492930;
			
			// aapt resource value: 0x7f0c003e
			public const int controls_container = 2131492926;
			
			// aapt resource value: 0x7f0c0045
			public const int controls_dock = 2131492933;
			
			// aapt resource value: 0x7f0c0040
			public const int current_time = 2131492928;
			
			// aapt resource value: 0x7f0c003c
			public const int description = 2131492924;
			
			// aapt resource value: 0x7f0c0043
			public const int description_dock = 2131492931;
			
			// aapt resource value: 0x7f0c0027
			public const int details_frame = 2131492903;
			
			// aapt resource value: 0x7f0c0028
			public const int details_overview = 2131492904;
			
			// aapt resource value: 0x7f0c002c
			public const int details_overview_actions = 2131492908;
			
			// aapt resource value: 0x7f0c002b
			public const int details_overview_description = 2131492907;
			
			// aapt resource value: 0x7f0c0029
			public const int details_overview_image = 2131492905;
			
			// aapt resource value: 0x7f0c002a
			public const int details_overview_right_panel = 2131492906;
			
			// aapt resource value: 0x7f0c0025
			public const int dummy = 2131492901;
			
			// aapt resource value: 0x7f0c002d
			public const int error_frame = 2131492909;
			
			// aapt resource value: 0x7f0c0015
			public const int extra = 2131492885;
			
			// aapt resource value: 0x7f0c0037
			public const int extra_badge = 2131492919;
			
			// aapt resource value: 0x7f0c0038
			public const int fade_mask = 2131492920;
			
			// aapt resource value: 0x7f0c0032
			public const int fade_out_edge = 2131492914;
			
			// aapt resource value: 0x7f0c0026
			public const int fragment_dock = 2131492902;
			
			// aapt resource value: 0x7f0c003a
			public const int hovercard_panel = 2131492922;
			
			// aapt resource value: 0x7f0c0021
			public const int icon = 2131492897;
			
			// aapt resource value: 0x7f0c002e
			public const int image = 2131492910;
			
			// aapt resource value: 0x7f0c0016
			public const int info = 2131492886;
			
			// aapt resource value: 0x7f0c000e
			public const int infoOver = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public const int infoUnder = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int infoUnderWithExtra = 2131492880;
			
			// aapt resource value: 0x7f0c0034
			public const int info_field = 2131492916;
			
			// aapt resource value: 0x7f0c0019
			public const int lb_action_button = 2131492889;
			
			// aapt resource value: 0x7f0c0000
			public const int lb_control_closed_captioning = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int lb_control_fast_forward = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int lb_control_fast_rewind = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int lb_control_high_quality = 2131492867;
			
			// aapt resource value: 0x7f0c0004
			public const int lb_control_more_actions = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int lb_control_play_pause = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int lb_control_repeat = 2131492870;
			
			// aapt resource value: 0x7f0c0007
			public const int lb_control_shuffle = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int lb_control_skip_next = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int lb_control_skip_previous = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public const int lb_control_thumbs_down = 2131492874;
			
			// aapt resource value: 0x7f0c000b
			public const int lb_control_thumbs_up = 2131492875;
			
			// aapt resource value: 0x7f0c0024
			public const int lb_details_description_body = 2131492900;
			
			// aapt resource value: 0x7f0c0023
			public const int lb_details_description_subtitle = 2131492899;
			
			// aapt resource value: 0x7f0c0022
			public const int lb_details_description_title = 2131492898;
			
			// aapt resource value: 0x7f0c000c
			public const int lb_focus_animator = 2131492876;
			
			// aapt resource value: 0x7f0c0050
			public const int lb_results_frame = 2131492944;
			
			// aapt resource value: 0x7f0c0048
			public const int lb_row_container_header_dock = 2131492936;
			
			// aapt resource value: 0x7f0c0051
			public const int lb_search_bar = 2131492945;
			
			// aapt resource value: 0x7f0c004d
			public const int lb_search_bar_badge = 2131492941;
			
			// aapt resource value: 0x7f0c004c
			public const int lb_search_bar_items = 2131492940;
			
			// aapt resource value: 0x7f0c004b
			public const int lb_search_bar_speech_orb = 2131492939;
			
			// aapt resource value: 0x7f0c004f
			public const int lb_search_frame = 2131492943;
			
			// aapt resource value: 0x7f0c004e
			public const int lb_search_text_editor = 2131492942;
			
			// aapt resource value: 0x7f0c0054
			public const int lb_shadow_focused = 2131492948;
			
			// aapt resource value: 0x7f0c0053
			public const int lb_shadow_normal = 2131492947;
			
			// aapt resource value: 0x7f0c000d
			public const int lb_slide_transition_value = 2131492877;
			
			// aapt resource value: 0x7f0c0017
			public const int main = 2131492887;
			
			// aapt resource value: 0x7f0c0011
			public const int mainOnly = 2131492881;
			
			// aapt resource value: 0x7f0c0033
			public const int main_image = 2131492915;
			
			// aapt resource value: 0x7f0c002f
			public const int message = 2131492911;
			
			// aapt resource value: 0x7f0c003f
			public const int more_actions_dock = 2131492927;
			
			// aapt resource value: 0x7f0c003d
			public const int playback_progress = 2131492925;
			
			// aapt resource value: 0x7f0c0039
			public const int row_content = 2131492921;
			
			// aapt resource value: 0x7f0c0030
			public const int row_header = 2131492912;
			
			// aapt resource value: 0x7f0c0049
			public const int scale_frame = 2131492937;
			
			// aapt resource value: 0x7f0c0052
			public const int search_orb = 2131492946;
			
			// aapt resource value: 0x7f0c0046
			public const int secondary_controls_dock = 2131492934;
			
			// aapt resource value: 0x7f0c0014
			public const int selected = 2131492884;
			
			// aapt resource value: 0x7f0c0044
			public const int spacer = 2131492932;
			
			// aapt resource value: 0x7f0c003b
			public const int title = 2131492923;
			
			// aapt resource value: 0x7f0c0035
			public const int title_text = 2131492917;
			
			// aapt resource value: 0x7f0c0041
			public const int total_time = 2131492929;
			
			// aapt resource value: 0x7f0c0018
			public const int wrap_content = 2131492888;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0d0000
			public const int lb_browse_headers_transition_delay = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int lb_browse_headers_transition_duration = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int lb_browse_rows_anim_duration = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int lb_card_activated_animation_duration = 2131558403;
			
			// aapt resource value: 0x7f0d0004
			public const int lb_card_selected_animation_delay = 2131558404;
			
			// aapt resource value: 0x7f0d0005
			public const int lb_card_selected_animation_duration = 2131558405;
			
			// aapt resource value: 0x7f0d0006
			public const int lb_details_description_body_max_lines = 2131558406;
			
			// aapt resource value: 0x7f0d0007
			public const int lb_details_description_body_min_lines = 2131558407;
			
			// aapt resource value: 0x7f0d0008
			public const int lb_details_description_subtitle_max_lines = 2131558408;
			
			// aapt resource value: 0x7f0d0009
			public const int lb_details_description_title_max_lines = 2131558409;
			
			// aapt resource value: 0x7f0d000a
			public const int lb_error_message_max_lines = 2131558410;
			
			// aapt resource value: 0x7f0d000b
			public const int lb_playback_bg_fade_in_ms = 2131558411;
			
			// aapt resource value: 0x7f0d000c
			public const int lb_playback_bg_fade_out_ms = 2131558412;
			
			// aapt resource value: 0x7f0d000d
			public const int lb_playback_controls_fade_in_ms = 2131558413;
			
			// aapt resource value: 0x7f0d000e
			public const int lb_playback_controls_fade_out_ms = 2131558414;
			
			// aapt resource value: 0x7f0d000f
			public const int lb_playback_controls_show_time_ms = 2131558415;
			
			// aapt resource value: 0x7f0d0010
			public const int lb_playback_description_fade_in_ms = 2131558416;
			
			// aapt resource value: 0x7f0d0011
			public const int lb_playback_description_fade_out_ms = 2131558417;
			
			// aapt resource value: 0x7f0d0012
			public const int lb_playback_rows_fade_delay_ms = 2131558418;
			
			// aapt resource value: 0x7f0d0013
			public const int lb_playback_rows_fade_in_ms = 2131558419;
			
			// aapt resource value: 0x7f0d0014
			public const int lb_playback_rows_fade_out_ms = 2131558420;
			
			// aapt resource value: 0x7f0d0015
			public const int lb_search_bar_speech_mode_background_alpha = 2131558421;
			
			// aapt resource value: 0x7f0d0016
			public const int lb_search_bar_text_mode_background_alpha = 2131558422;
			
			// aapt resource value: 0x7f0d0017
			public const int lb_search_orb_pulse_duration_ms = 2131558423;
			
			// aapt resource value: 0x7f0d0018
			public const int lb_search_orb_scale_duration_ms = 2131558424;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int lb_action_1_line = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int lb_action_2_lines = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int lb_background_window = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int lb_browse_fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int lb_browse_title = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int lb_card_color_overlay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int lb_control_bar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int lb_control_button_primary = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int lb_control_button_secondary = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int lb_details_description = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int lb_details_fragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int lb_details_overview = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int lb_error_fragment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int lb_header = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int lb_headers_fragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int lb_image_card_view = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int lb_list_row = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int lb_list_row_hovercard = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int lb_playback_controls = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int lb_playback_controls_row = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int lb_row_container = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int lb_row_header = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int lb_rows_fragment = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int lb_search_bar = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int lb_search_fragment = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int lb_search_orb = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int lb_shadow = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int lb_speech_orb = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int lb_title_view = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int lb_vertical_grid = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int lb_vertical_grid_fragment = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Main = 2130903071;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int lb_voice_failure = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int lb_voice_no_input = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int lb_voice_open = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int lb_voice_success = 2131099651;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001c
			public const int ApplicationName = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int Hello = 2131165211;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int lb_playback_controls_closed_captioning_disable = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int lb_playback_controls_closed_captioning_enable = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int lb_playback_controls_fast_forward = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int lb_playback_controls_high_quality_disable = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int lb_playback_controls_high_quality_enable = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int lb_playback_controls_more_actions = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int lb_playback_controls_pause = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int lb_playback_controls_play = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int lb_playback_controls_repeat_all = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int lb_playback_controls_repeat_none = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int lb_playback_controls_repeat_one = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int lb_playback_controls_rewind = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int lb_playback_controls_shuffle_disable = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int lb_playback_controls_shuffle_enable = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int lb_playback_controls_skip_next = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int lb_playback_controls_skip_previous = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int lb_playback_controls_thumb_down = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int lb_playback_controls_thumb_down_outline = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int lb_playback_controls_thumb_up = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int lb_playback_controls_thumb_up_outline = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int lb_search_bar_hint = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int lb_search_bar_hint_speech = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int lb_search_bar_hint_with_title = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int lb_search_bar_hint_with_title_speech = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int orb_search_action = 2131165210;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Mono_Android_Theme_Splash = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Leanback = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Leanback_DetailsActionButton = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Leanback_DetailsDescriptionBody = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Leanback_DetailsDescriptionSubtitle = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Leanback_DetailsDescriptionTitle = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Leanback_ErrorMessage = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Leanback_Header = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Leanback_PlaybackControlsTime = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int TextAppearance_Leanback_Row_Header = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int TextAppearance_Leanback_Row_HoverCardDescription = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Leanback_Row_HoverCardTitle = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int TextAppearance_Leanback_SearchTextEdit = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int TextAppearance_Leanback_Title = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int TextAppearance_LeanbackBase = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int Theme_Leanback = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int Theme_LeanbackBase = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int Widget_Leanback = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int Widget_Leanback_BaseCardViewStyle = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int Widget_Leanback_DetailsActionButtonStyle = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int Widget_Leanback_DetailsActionButtonStyleBase = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int Widget_Leanback_DetailsDescriptionBodyStyle = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int Widget_Leanback_DetailsDescriptionSubtitleStyle = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int Widget_Leanback_DetailsDescriptionTitleStyle = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int Widget_Leanback_ErrorMessageStyle = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int Widget_Leanback_GridItems = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int Widget_Leanback_GridItems_VerticalGridView = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int Widget_Leanback_Header = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int Widget_Leanback_Headers = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int Widget_Leanback_Headers_VerticalGridView = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int Widget_Leanback_ImageCardViewStyle = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int Widget_Leanback_PlaybackControlsActionIconsStyle = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int Widget_Leanback_PlaybackControlsButtonStyle = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int Widget_Leanback_PlaybackControlsTimeStyle = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int Widget_Leanback_Row = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int Widget_Leanback_Row_Header = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int Widget_Leanback_Row_HorizontalGridView = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int Widget_Leanback_Row_HoverCardDescription = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int Widget_Leanback_Row_HoverCardTitle = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int Widget_Leanback_Rows = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int Widget_Leanback_Rows_VerticalGridView = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int Widget_Leanback_SearchOrbViewStyle = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int Widget_Leanback_Title = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int Widget_Leanback_Title_Icon = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int Widget_Leanback_Title_Text = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int Widget_Leanback_TitleView = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int Widget_LeanbackBase = 2131230766;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Transition
		{
			
			// aapt resource value: 0x7f050000
			public const int lb_enter_transition = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int lb_return_transition = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int lb_shared_element_enter_transition = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int lb_shared_element_return_transition = 2131034115;
			
			static Transition()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Transition()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LeanbackTheme = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 17
			public const int LeanbackTheme_baseCardViewStyle = 17;
			
			// aapt resource value: 3
			public const int LeanbackTheme_browsePaddingBottom = 3;
			
			// aapt resource value: 0
			public const int LeanbackTheme_browsePaddingLeft = 0;
			
			// aapt resource value: 1
			public const int LeanbackTheme_browsePaddingRight = 1;
			
			// aapt resource value: 2
			public const int LeanbackTheme_browsePaddingTop = 2;
			
			// aapt resource value: 6
			public const int LeanbackTheme_browseRowsFadingEdgeLength = 6;
			
			// aapt resource value: 4
			public const int LeanbackTheme_browseRowsMarginStart = 4;
			
			// aapt resource value: 5
			public const int LeanbackTheme_browseRowsMarginTop = 5;
			
			// aapt resource value: 8
			public const int LeanbackTheme_browseTitleIconStyle = 8;
			
			// aapt resource value: 7
			public const int LeanbackTheme_browseTitleTextStyle = 7;
			
			// aapt resource value: 9
			public const int LeanbackTheme_browseTitleViewStyle = 9;
			
			// aapt resource value: 27
			public const int LeanbackTheme_defaultBrandColor = 27;
			
			// aapt resource value: 29
			public const int LeanbackTheme_defaultSearchBrightColor = 29;
			
			// aapt resource value: 28
			public const int LeanbackTheme_defaultSearchColor = 28;
			
			// aapt resource value: 31
			public const int LeanbackTheme_defaultSearchIcon = 31;
			
			// aapt resource value: 22
			public const int LeanbackTheme_detailsActionButtonStyle = 22;
			
			// aapt resource value: 21
			public const int LeanbackTheme_detailsDescriptionBodyStyle = 21;
			
			// aapt resource value: 20
			public const int LeanbackTheme_detailsDescriptionSubtitleStyle = 20;
			
			// aapt resource value: 19
			public const int LeanbackTheme_detailsDescriptionTitleStyle = 19;
			
			// aapt resource value: 26
			public const int LeanbackTheme_errorMessageStyle = 26;
			
			// aapt resource value: 11
			public const int LeanbackTheme_headerStyle = 11;
			
			// aapt resource value: 10
			public const int LeanbackTheme_headersVerticalGridStyle = 10;
			
			// aapt resource value: 18
			public const int LeanbackTheme_imageCardViewStyle = 18;
			
			// aapt resource value: 25
			public const int LeanbackTheme_itemsVerticalGridStyle = 25;
			
			// aapt resource value: 36
			public const int LeanbackTheme_overlayDimActiveLevel = 36;
			
			// aapt resource value: 37
			public const int LeanbackTheme_overlayDimDimmedLevel = 37;
			
			// aapt resource value: 35
			public const int LeanbackTheme_overlayDimMaskColor = 35;
			
			// aapt resource value: 34
			public const int LeanbackTheme_playbackControlsActionIcons = 34;
			
			// aapt resource value: 23
			public const int LeanbackTheme_playbackControlsButtonStyle = 23;
			
			// aapt resource value: 33
			public const int LeanbackTheme_playbackControlsIconHighlightColor = 33;
			
			// aapt resource value: 24
			public const int LeanbackTheme_playbackControlsTimeStyle = 24;
			
			// aapt resource value: 32
			public const int LeanbackTheme_playbackProgressPrimaryColor = 32;
			
			// aapt resource value: 14
			public const int LeanbackTheme_rowHeaderStyle = 14;
			
			// aapt resource value: 13
			public const int LeanbackTheme_rowHorizontalGridStyle = 13;
			
			// aapt resource value: 16
			public const int LeanbackTheme_rowHoverCardDescriptionStyle = 16;
			
			// aapt resource value: 15
			public const int LeanbackTheme_rowHoverCardTitleStyle = 15;
			
			// aapt resource value: 12
			public const int LeanbackTheme_rowsVerticalGridStyle = 12;
			
			// aapt resource value: 30
			public const int LeanbackTheme_searchOrbViewStyle = 30;
			
			public static int[] lbBaseCardView = new int[] {
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011};
			
			// aapt resource value: 5
			public const int lbBaseCardView_activatedAnimationDuration = 5;
			
			// aapt resource value: 0
			public const int lbBaseCardView_cardType = 0;
			
			// aapt resource value: 2
			public const int lbBaseCardView_extraVisibility = 2;
			
			// aapt resource value: 1
			public const int lbBaseCardView_infoVisibility = 1;
			
			// aapt resource value: 3
			public const int lbBaseCardView_selectedAnimationDelay = 3;
			
			// aapt resource value: 4
			public const int lbBaseCardView_selectedAnimationDuration = 4;
			
			public static int[] lbBaseCardView_Layout = new int[] {
					2130772012};
			
			// aapt resource value: 0
			public const int lbBaseCardView_Layout_layout_viewType = 0;
			
			public static int[] lbBaseGridView = new int[] {
					16842927,
					2130772013,
					2130772014,
					2130772015,
					2130772016};
			
			// aapt resource value: 0
			public const int lbBaseGridView_android_gravity = 0;
			
			// aapt resource value: 2
			public const int lbBaseGridView_focusOutEnd = 2;
			
			// aapt resource value: 1
			public const int lbBaseGridView_focusOutFront = 1;
			
			// aapt resource value: 3
			public const int lbBaseGridView_horizontalMargin = 3;
			
			// aapt resource value: 4
			public const int lbBaseGridView_verticalMargin = 4;
			
			public static int[] lbHorizontalGridView = new int[] {
					2130772017,
					2130772018};
			
			// aapt resource value: 1
			public const int lbHorizontalGridView_numberOfRows = 1;
			
			// aapt resource value: 0
			public const int lbHorizontalGridView_rowHeight = 0;
			
			public static int[] lbImageCardView = new int[] {
					2130772019};
			
			// aapt resource value: 0
			public const int lbImageCardView_infoAreaBackground = 0;
			
			public static int[] lbPlaybackControlsActionIcons = new int[] {
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034};
			
			// aapt resource value: 14
			public const int lbPlaybackControlsActionIcons_closed_captioning = 14;
			
			// aapt resource value: 2
			public const int lbPlaybackControlsActionIcons_fast_forward = 2;
			
			// aapt resource value: 13
			public const int lbPlaybackControlsActionIcons_high_quality = 13;
			
			// aapt resource value: 1
			public const int lbPlaybackControlsActionIcons_pause = 1;
			
			// aapt resource value: 0
			public const int lbPlaybackControlsActionIcons_play = 0;
			
			// aapt resource value: 10
			public const int lbPlaybackControlsActionIcons_repeat = 10;
			
			// aapt resource value: 11
			public const int lbPlaybackControlsActionIcons_repeat_one = 11;
			
			// aapt resource value: 3
			public const int lbPlaybackControlsActionIcons_rewind = 3;
			
			// aapt resource value: 12
			public const int lbPlaybackControlsActionIcons_shuffle = 12;
			
			// aapt resource value: 4
			public const int lbPlaybackControlsActionIcons_skip_next = 4;
			
			// aapt resource value: 5
			public const int lbPlaybackControlsActionIcons_skip_previous = 5;
			
			// aapt resource value: 9
			public const int lbPlaybackControlsActionIcons_thumb_down = 9;
			
			// aapt resource value: 8
			public const int lbPlaybackControlsActionIcons_thumb_down_outline = 8;
			
			// aapt resource value: 7
			public const int lbPlaybackControlsActionIcons_thumb_up = 7;
			
			// aapt resource value: 6
			public const int lbPlaybackControlsActionIcons_thumb_up_outline = 6;
			
			public static int[] lbSearchOrbView = new int[] {
					2130772035,
					2130772036,
					2130772037,
					2130772038};
			
			// aapt resource value: 3
			public const int lbSearchOrbView_searchOrbBrightColor = 3;
			
			// aapt resource value: 2
			public const int lbSearchOrbView_searchOrbColor = 2;
			
			// aapt resource value: 0
			public const int lbSearchOrbView_searchOrbIcon = 0;
			
			// aapt resource value: 1
			public const int lbSearchOrbView_searchOrbIconColor = 1;
			
			public static int[] lbVerticalGridView = new int[] {
					2130772039,
					2130772040};
			
			// aapt resource value: 0
			public const int lbVerticalGridView_columnWidth = 0;
			
			// aapt resource value: 1
			public const int lbVerticalGridView_numberOfColumns = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
