#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JoyReactor.Android.Resource", IsApplication=true)]

namespace JoyReactor.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::JoyReactor.Android.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::JoyReactor.Android.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::JoyReactor.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::JoyReactor.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int List = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Pager = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int Progress = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int about = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int action = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int animator = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int content = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int count = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int createAccount = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int group = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int groupTitle = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int icon = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int image = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int login = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int password = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int profile = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int settings = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int sources = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int stub = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int title = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int user_image = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int user_name = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int username = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityHome = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivityPost = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_profile = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FragmentFeed = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FragmentLeftMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ItemFeed = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ItemSubscription = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int home = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
